### ISSUE TITLE
Deconvolution vs Upsampling

### ISSUE THREAD

**Issue by ghost** [zo7/deconvfaces#1]
Hi,

Awesome results, congrats!

I notice that in the blog post you talk about deconvolution layers, but then in the code I see you use the Upsampling2D layer instead of the Deconvolution2D. Why this choice?

Thanks!

**Comment by flynnmd** [comment]
Oh interesting. I actually did this project way back in the spring and only just recently returned to it to see if I could get higher-resolution outputs. I don't think the Deconvolution2D layer was available in Keras when I first wrote the code for the model. I think I'd prefer sticking with explicitly upsampling and convolving since here I'm using two layers of conv (5x5 kernels followed by 3x3) for the entire deconvolution process.

I'm not aware if one is more efficient over the other though (I doubt it)
