### ISSUE TITLE
keras, tensorflow, theano versions?

### ISSUE THREAD

**Issue by welch** [zo7/deconvfaces#11]
Hi,

I'm tripping over a few 'module has no attribute' errors that may simply be version incompatibilities (I'm working from a fresh install of everything). Can you include version info for your major dependencies in the README?

Thanks

**Comment by flynnmd** [comment]
Oh weird, I just added a requirements.txt if you want to try that. (which I should have had to begin with!) I tried running it from a fresh virtualenv with Python 3.5 and it seemed to work.

What was the exact error you were getting? One thing is that I typically use the TensorFlow backend, so there might be bugs if you're using Theano instead. I didn't include TensorFlow in the requirements.txt since it's not managed through PyPI and is platform-dependent, but you can try installing that if you run into problems.

**Comment by welch** [comment]
I was attempting this under python2.7, as scipy 0.18.x for python3 on macos has issues, and I fell back just in case this could be made to work in my healthier 2.7 env. I am currently re-installing 3.5 with scipy 0.17.0 0 as a workaround, we'll see how far I get.

(Did not look into 2/3 compatibilities, but the missing items were keras.models.load_model plus several items from keras.backend incl image_dim_ordering)

**Comment by welch** [comment]
all better now, a training run succeeded (python 3.5, scipy 0.17.0).
I did need to manually install h5py, it's optional for keras
and is needed for save_model.

**Comment by flynnmd** [comment]
@welch Cool! Glad it's working for you.
