### ISSUE TITLE
How to build a Holodeck with this

### ISSUE THREAD

**Issue by kaihuchen** [zo7/deconvfaces#7]
I have been contemplating on what it takes in order to produce 3D objects/environments from interactive verbal commands (somewhat similar to the Star Trek Holodeck scenario, see my drat blog here: http://www.terraai.org/tag/holodeck/index.html), and this technology seems to be a reasonble starting point for that. 

How's so? Because if you are able to create good interpolation between images with lighting/poses, then next step is to be able to interpolate parts (like: Computer, make the nose more like Nicole Kidman's), then pushed further to interpolate spatial constraints (like: Computer, put the chair on top of the desk), followed by conversion to full 3D for deployment to a VR device, the there you have a simple Holodeck!

The reasonable next step is probably about dealing with parts. Anybody has thoughts about how to get there? I figure the masking capability mentioned in the original paper would be vital here.

**Comment by kaihuchen** [comment]
Towards such a goal, we need to enhance deconvfaces to make it good at extrapolation (i.e., generalization) as well, and not just good at interpolating between given images.

More specifically, this means supporting the following capability:
1. Train on a number of identities, with different poses, lighting conditions, emotions, etc., in order to create a model M.
2. When given the single picture of an unseen face F, use M to generate an entire set of images for different poses, emotions, and lightings for F.

I wonder what it would take in order to make this happen.

**Comment by flynnmd** [comment]
I think you're overestimating what this model can do -- it really can only just interpolate between known examples because that's all it knows. Otherwise it's very limited and its abilities are constrained by the data that you use. You can get interesting output by mixing inputs or giving it nonsensical inputs, but that's about it, it's inherent in the architecture.

Something like generative adversarial networks or a model that produces images based on text input might be better suited for what you're asking, but it's not in the scope of this project.

**Comment by kaihuchen** [comment]
@zo7  I understand that this model is limited as you described. I was just thinking aloud about how to push it to the next stage. One way to achieve generalization is to bring over some constraints found in the higher layers of the convolution side and impose those on the deconvolution side, which should create some effects of generalization. Anyways, if there is no interest here I will explore this separately.
